model_checkpoint:
    _target_: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
    # monitor: 'val/Loss_comb'  
    # save_top_k: 1
    # auto_insert_metric_name: False
    save_last: False
    every_n_epochs: 1
    verbose: True
    save_weights_only: True
    save_on_train_epoch_end: True
    # mode: "min"
    dirpath: "/workspace/data/checkpoints/"
    filename: "epoch-{epoch}_step-{step}"
